---
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: pod - fields - hostUsers
templates:
  - common.yaml
values:
  - ../_values/controllers_main_default_container.yaml
tests:
  - it: should not be present by default
    documentSelector:
      path: $[?(@.kind == "Deployment")].metadata.name
      value: release-name
    asserts:
      - notExists:
          path: spec.template.spec.hostUsers

  - it: hostUsers disabled can be configured
    set:
      defaultPodOptions:
        hostUsers: false
    documentSelector:
      path: $[?(@.kind == "Deployment")].metadata.name
      value: release-name
    asserts:
      - equal:
          path: spec.template.spec.hostUsers
          value: false

  - it: hostUsers enabled can be configured
    set:
      defaultPodOptions:
        hostUsers: true
    documentSelector:
      path: $[?(@.kind == "Deployment")].metadata.name
      value: release-name
    asserts:
      - equal:
          path: spec.template.spec.hostUsers
          value: true
