---
apiVersion: v2
name: common
description: Function library for Helm charts
type: library
version: 5.0.0
kubeVersion: ">=1.31.0-0"
keywords:
  - common
  - library
home: https://github.com/bjw-s-labs/helm-charts/tree/main/charts/library/common
maintainers:
  - name: bjw-s
    email: me@bjw-s.dev
sources:
  - https://github.com/bjw-s-labs/helm-charts
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: |-
        Minimum required Kubernetes version has been increased to 1.31
    - kind: fixed
      description: |-
        Improve error messages
    - kind: fixed
      description: |-
        Fix edge case in volumeMounts where default persistence type was not properly set
    - kind: fixed
      description: |-
        Fix whitespace handling in Route backendRefs
