---
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: container - validations
templates:
  - common.yaml
values:
  - ../_values/controllers_main_default_container.yaml
tests:
  - it: image repository is required
    set:
      controllers:
        main:
          containers:
            test:
              image:
                repository: ""
                tag: "test"
    asserts:
      - failedTemplate:
          errorMessage: "Container 'test': Image repository is required. Specify the repository under 'controllers.main.containers.test.image.repository'."

  - it: image tag is required
    set:
      controllers:
        main:
          containers:
            test:
              image:
                repository: test
                tag: ""
    asserts:
      - failedTemplate:
          errorMessage: "Container 'test': Either image tag or digest is required. Specify a tag or digest under 'controllers.main.containers.test.image'."
